// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgnvcmkkddwmchmjaypu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnbnZjbWtrZGR3bWNobWpheXB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNjkzMjIsImV4cCI6MjA2NTY0NTMyMn0.Q1aFXYAzz5RATGx2tVKIarfHXJ3B5-TrVHofKnUekus";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);